version: "3.8"

services:
  fenland_trajectory_agent:
    image: ghcr.io/cambridge-cares/fenland_trajectory_agent:1.0.0-SNAPSHOT
    environment:
      - STACK_NAME=${STACK_NAME}
      # Target Blazegraph namespace
      - DB_URL=jdbc:postgresql://host.docker.internal:3840/postgres
      - SPARQL_QUERY_ENDPOINT=http://host.docker.internal:3840/blazegraph/namespace/gps_trajectory/sparql
      - SPARQL_UPDATE_ENDPOINT=http://host.docker.internal:3840/blazegraph/namespace/gps_trajectory/sparql
      - NAMESPACE=gps_trajectory
      # Target layer name in geoserver, also table name in PostGIS
      - LAYERNAME=gps_trajectory
      # Target PostGIS/PostgreSQL database name
      # (default name "postgres" required for Ontop to work)
      - DATABASE=postgres
      - GEOSERVER_WORKSPACE=gps_trajectory
      - ONTOP_FILE=/app/resources/ontop.obda
    ports:
      - "5000:5000"
    volumes:
      # Link container output directory to local directory to access output files
      # (i.e. only required for creation of output geojson files)
      - ./output:/app/output
      - logs:/root/.jps
    configs:
      - blazegraph
      - geoserver
      - ontop
      - postgis
    secrets:
      - geoserver_password
      - postgis_password

volumes:
  logs:
    name: "logs"
